echo off
echo    **********  -= WARNING =-   **************
echo This Batch file will REROLL THE GAME!
echo It will also erase ALL *.SAV and *.MSG files in the
echo current DIRECTORY!
echo
echo
echo    *********** -=  HIT Ctrl-C if you do NOT want this  =-  ***********
pause
erase *.SAV
erase *.MSG
clocxy
ctable
cmmouth
echo The Game has been rerolled, it is now ready to be started!
